[package]
name = "ws-live-server"
version = "0.1.0"
authors = ["shell <asypost@yeah.net>"]
edition = "2018"

[dependencies]
ws = "0.7.9"
url = "1.7.2"
clap = "2.32.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
codegen-units = 1